server.servlet.context-path: /api

app:
  duracaoSessao: ${DURACAO_SESSAO_MINUTOS:1}

management.tracing.enabled: true

spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties.hibernate.format_sql: true
  datasource:
    url: ${DB_URL:jdbc:sqlite:src/main/resources/desafio.db}
    username: ${DB_USER:sa}
    password: ${DB_PASS:sa}
  liquibase:
    url: ${DB_URL:jdbc:sqlite:src/main/resources/desafio.db}
    user: ${DB_USER:sa}
    password: ${DB_PASS:sa}
    change-log: classpath:db/changelog/db.changelog-master.xml
