server.servlet.context-path: /api

spring:
  jpa:
    open-in-view: false
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:sqlite:src/main/resources/desafio.db
    username: sa
    password: sa
  liquibase:
    url: jdbc:sqlite:src/main/resources/desafio.db
    user: sa
    password: sa
    change-log: classpath:db/changelog/db.changelog-master.xml
